
export const SUPABASE_URL = "https://kczezulhpklofnibgarp.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjemV6dWxocGtsb2ZuaWJnYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTM4MDcsImV4cCI6MjA2MzcyOTgwN30.uVVDMNPzlbxPAYcv9aO7HwItybKkifxlz-XRYLhF_8o";
