// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kczezulhpklofnibgarp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjemV6dWxocGtsb2ZuaWJnYXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTM4MDcsImV4cCI6MjA2MzcyOTgwN30.uVVDMNPzlbxPAYcv9aO7HwItybKkifxlz-XRYLhF_8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);